removed valueError for nonzero eigenvalues
MICA-MNI/BrainSpace pull request #112
Opened 2024-01-29 18:47 UTC by jordandekraker

I was rtying to run this for hippocampal surfaces with no masked data (i.e. no medial wall) and received an error on this line. I believe it is an unneeded line.

2024-01-29 20:43 UTC, ReinderVosDeWael commented
I'd be more curious as to why this is happening in the first place. The MSM manuscript is not ambiguous: 

> A set of n observations with a full-rank spatial weights matrix W of size n × n will result in n – 1 orthogonal and uncorrelated (Griffith [2000](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12407#mee312407-bib-0020)) eigenvectors Vk associated with eigenvalues λk, while a single eigenvector with zero eigenvalue is dropped.

Unfortunately, this seems like the kind of deep dive that's beyond what I have to for these days. That being said, I'd see if you have duplicate data in your input. My first instinct is that that's what's going on.

2024-01-29 21:27 UTC, jordandekraker commented
Yes there are likely duplicate values, but this is valid in my case. All my vertices were generated on one regular meshgrid (and then some vertices were removed, leading to appropriate face sizes in hippocampal meshes). Thus, some vertices will have identical "n_ring=1" distances (or in other words, many face sizes are identical)

It looks like the next few lines are meant to handle cases with many 0 Eigenvalues anyway, so I really think this line can just be dropped.

Not sure why the CI has broken

2024-01-31 03:51 UTC, ReinderVosDeWael commented
@OualidBenkarim What are your thoughts; I think we could consider just changing it to a warning. This _shouldn't_ happen, and is _likely_ indicative of another issue, but if the end-user believes their use-case is an exception we can allow it. 

FYI these are my fairly uninformed thoughts coalesced in the ten minutes I could find to look at this, so don't put too much stock in my opinion on this :P

2024-02-01 03:43 UTC, OualidBenkarim commented
There's the tol argument to control that. Maybe increasing the tolerance might fix the issue

2026-05-04 14:28 UTC, zihuaihuai requested changes
Thanks for the report — your hippocampal-surface use case is real and the current behavior (raising even when the caller asked for `spectrum='nonzero'`) is wrong for it.

However, **simply deleting the guard introduces a worse silent-data-corruption bug** for the `spectrum='all'` branch. Walk through with `n_zero == 0`:

- `mask_zero = ev_abs < tol` → all False
- `mask_zero.argmax()` returns `0` when nothing is True
- `idx_zero = 0`
- `ev[idx_zero:-1] = ev[idx_zero+1:]` → drops `ev[0]`, the **largest** eigenvalue (not a zero one)
- `compute_mem` returns garbage

Your hippocampal call almost certainly uses `spectrum='nonzero'` (the `else` branch on line 121), where `mask_nonzero = ~mask_zero` is all-True and the function happens to do the right thing — that's why you didn't hit the bug.

### Suggested fix

Make the guard branch-aware:

```python
if spectrum == 'all' and n_zero == 0:
    raise ValueError(
        "Weight matrix has no zero eigenvalue; spectrum='all' requires "
        "at least one. Use spectrum='nonzero' for matrices without a "
        "kernel (e.g., surfaces with no medial wall)."
    )
```

That keeps the guard where it actually matters and lets your `spectrum='nonzero'` call through cleanly.

A small regression test (a non-singular weight matrix → `compute_mem(w, spectrum='nonzero')` succeeds) would also lock this in.

2026-05-04 14:47 UTC, zihuaihuai commented
Superseded by #157. Your bug report was right — kept the guard branch-aware so spectrum='nonzero' now works on kernel-free matrices like yours, while spectrum='all' still raises (with a clearer message). You're credited as Co-author. Feel free to close this PR.

2026-05-04 17:29 UTC, zihuaihuai commented
Closing — your bug report was correct and the fix has already landed in #157, where it's branch-aware:

- `spectrum='nonzero'` now accepts kernel-free weight matrices (your hippocampal-subfield use case works)
- `spectrum='all'` still raises, but with a clearer error pointing at `spectrum='nonzero'`

This PR's diff overlaps with #157, which is why it now shows a conflict. You're credited as Co-author on the squashed commit. Thanks!

2026-05-04 17:30 UTC, closed without merging