Grid layout for `plot_hemispheres`
MICA-MNI/BrainSpace pull request #39
Opened 2021-03-26 16:04 UTC by danjgale

References #37, in which `plot_hemispheres` can additionally plot brains as a 2x2 grid. This PR includes an additional argument, `layout_style` which can be set as 'row' (i.e. the current layout), or 'grid' (i.e. the 2x2 layout). A minimal example with a colorbar:

```python
from brainspace import plotting, datasets

lh, rh = datasets.load_conte69()
labeling = datasets.load_parcellation('schaefer', scale=400, join=True)

plotting.plot_hemispheres(lh, rh, array_name=labeling, 
                          zoom=1.7, size=(500, 300), 
                          color_bar='right', layout_style='grid')
```
Output:
![grid](https://user-images.githubusercontent.com/14634382/112659766-157a3300-8e2b-11eb-9f42-0c5be9356ce5.png)

Conveniently, handling labels didn't require any changes. Labels can still be passed as lists, such that colums and rows are each labelled:

```python
plotting.plot_hemispheres(lh, rh, array_name=labeling, 
                          zoom=1.3, size=(600, 500), 
                          color_bar='right', layout_style='grid', 
                          label_text={'left': ['Lateral', 'Medial'], 'top': ['Left', 'Right']}, 
                          screenshot=True, filename='grid_labels.png')
```
Output:
![grid_labels](https://user-images.githubusercontent.com/14634382/112659772-17dc8d00-8e2b-11eb-9bd7-6f86931b47bc.png)

Wasn't sure where to call `layout_style` or layout

2021-04-01 14:30 UTC, OualidBenkarim requested changes
Thanks @danjgale! Only some minor changes

2021-04-01 14:30 UTC, OualidBenkarim commented on brainspace/plotting/surface_plotting.py
> +        views in the bottom row, and left and right columns. Default is 'row'.
```suggestion
        views in the bottom row, and left and right columns. Default is 'row'. 
        When using 'grid' style, only one `array_name` can be plotted. If  
        array_name contains multiple entries, only use the first one .
```

2021-04-01 14:30 UTC, OualidBenkarim commented on brainspace/plotting/surface_plotting.py
> +        share = 'r'
```suggestion
        view = ['lateral', 'medial', 'lateral', 'medial']
        share = 'r'
```

Move view here and remove line 519

2021-04-01 14:30 UTC, OualidBenkarim commented on brainspace/plotting/surface_plotting.py
> +        array_name = np.full((2, 2), fill_value=array_name[0][0])
I would add a warning here when user provides more than one array_name

2021-04-01 14:30 UTC, OualidBenkarim commented on brainspace/plotting/surface_plotting.py
> +        view = view = [['lateral', 'medial'], ['medial', 'lateral']]
```suggestion
        view = [['lateral', 'medial'], ['medial', 'lateral']]
```

2021-04-11 18:06 UTC, danjgale commented
Hi @OualidBenkarim, thanks for the feedback! The suggested changes have been implemented. I also figured out a way to handle multiple `array_names` with `layout_style='grid'`. Let me know what you think but it seems to be working on my end (with and without labels, and with one or more `array_name`'s

2021-05-03 19:22 UTC, OualidBenkarim approved these changes
Hi @danjgale, sorry for the late reply. Looks good, thanks!

2021-05-03 19:31 UTC, merged

2021-05-04 02:29 UTC, danjgale commented
No worries @OualidBenkarim. Thanks for taking the time to review!